/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  blog: [
    'blog/introduction',
    {
      label: 'Docusaurus',
      type: 'category',
      link: {
        type: 'doc',
        id: 'blog/Docusaurus/Docusaurus-guides'
      },
      items: [
        'blog/Docusaurus/Docusaurus-环境配置',
        'blog/Docusaurus/Docusaurus-部署',
        'blog/Docusaurus/Docusaurus-样式与页面',
        'blog/Docusaurus/Docusaurus-自定义组件',
        'blog/Docusaurus/Docusaurus-搜索配置',
        'blog/Docusaurus/Docusaurus-评论系统',
        'blog/Docusaurus/Docusaurus-图床配置',
        'blog/Docusaurus/Docusaurus-文档编辑指南',
        'blog/Docusaurus/Docusaurus-使用Hygen创建文章模板',
      ],
    },
    {
      label: 'Hexo',
      type: 'category',
      link: {
        type: 'doc',
        id: 'blog/Hexo/Hexo-guides'
      },
      items: [
        'blog/Hexo/Hexo-环境配置',
        'blog/Hexo/Hexo-部署',
        'blog/Hexo/Hexo-Vercel部署',
        'blog/Hexo/Hexo-主题安装',
      ],
    },
    {
      label: '网站小技巧',
      type: 'category',
      link: {
        // title: '',
        // description: '记录一些网站的使用小技巧',
        type: 'generated-index',
      },
      items: [
        { 
          type: 'autogenerated',
          dirName: 'blog/Tips',
        },
      ],
    },
  ],
  stack: [
    'stack/introduction',
    {
      label: 'Docusaurus 主题魔改',
      type: 'category',
      link: {
        type: 'doc',
        id: 'stack/docusaurus/docusaurus-guides'
      },
      items: [
        'stack/docusaurus/docusaurus-config',
        'stack/docusaurus/docusaurus-style',
        'stack/docusaurus/docusaurus-component',
        'stack/docusaurus/docusaurus-plugin',
        'stack/docusaurus/docusaurus-search',
        'stack/docusaurus/docusaurus-comment',
        'stack/docusaurus/docusaurus-deploy',
      ],
    },
    {
      label: '代码规范',
      type: 'category',
      link: {
        type: 'doc',
        id: 'stack/code-specification/code-specification-guides'
      },
      items: [
        'stack/code-specification/eslint',
        'stack/code-specification/prettier',
        'stack/code-specification/stylelint',
        'stack/code-specification/editorconfig',
        'stack/code-specification/husky',
        'stack/code-specification/npmrc',
      ],
    },
    {
      label: 'Vue',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        'stack/vue/vue-reactive-data-object',
        'stack/vue/vue-reactive-data-array',
        'stack/vue/vue-reactive-data-basic-type',
        'stack/vue/pinia',
      ],
    },
    {
      label: 'React',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'stack/react',
        },
      ],
    },
    {
      label: 'Web',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'stack/web',
        },
      ],
    },
    {
      label: 'JavaScript',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'stack/js',
        },
      ],
    },
    {
      label: 'Node',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'stack/node',
        },
      ],
    },
    {
      label: 'Css',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'stack/css',
        },
      ],
    },
    {
      label: 'Java',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'stack/java',
        },
      ],
    },
    {
      label: 'Python',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'stack/python',
        },
      ],
    },
    {
      label: 'Go',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        'stack/go/go-environment-install',
        'stack/go/go-json-usage',
        'stack/go/go-send-http-request',
        'stack/go/go-call-js',
        'stack/go/go-concurrent',
        'stack/go/try-gin-framework'
      ],
    },
    {
      label: 'Git',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'stack/git',
        },
      ],
    },
    {
      label: '算法',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'stack/algorithm',
        },
      ],
    },
    {
      label: '逆向',
      type: 'category',
      link: {
        title: '逆向笔记',
        description: 'Web逆向与安卓逆向笔记',
        type: 'generated-index',
        keywords: ['reverse', 'web', 'android', 'frida'],
      },
      items: [
        {
          label: '安卓',
          type: 'category',
          link: {
            type: 'generated-index',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'stack/reverse/android',
            },
          ],
        },
        {
          label: 'Web',
          type: 'category',
          items: [
            {
              type: 'autogenerated',
              dirName: 'stack/reverse/web',
            },
          ],
        },
        {
          label: '密码学',
          type: 'category',
          items: [
            {
              type: 'autogenerated',
              dirName: 'stack/reverse/crypto',
            },
          ],
        },
      ],
    },
    {
      label: 'Docker',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'stack/docker',
        },
      ],
    },
    {
      label: '数据库',
      type: 'category',
      link: {
        // title: '',
        // description: '',
        type: 'generated-index',
        keywords: ['database', 'mysql', 'mongodb', 'redis', 'elasticsearch'],
      },
      items: [
        {
          label: 'Mysql',
          type: 'category',
          link: {
            type: 'doc',
            id: 'stack/database/mysql/mysql-note',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'stack/database/mysql',
            },
          ],
        },
        {
          label: 'MongoDB',
          type: 'category',
          link: {
            type: 'doc',
            id: 'stack/database/mongo/mongodb-note',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'stack/database/mongo',
            },
          ],
        },
        {
          label: 'Redis',
          type: 'category',
          link: {
            type: 'doc',
            id: 'stack/database/redis/redis-note',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'stack/database/redis',
            },
          ],
        },
        {
          label: 'Elasticsearch',
          type: 'category',
          link: {
            type: 'doc',
            id: 'stack/database/elasticsearch/elasticsearch-note',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'stack/database/elasticsearch',
            },
          ],
        },
      ],
    },
    {
      label: '杂项',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'stack/other',
        },
      ],
    },
  ],
}

module.exports = sidebars
