/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  blog: [
    'blog/introduction',
    {
      label: 'Docusaurus',
      type: 'category',
      link: {
        type: 'doc',
        id: 'blog/Docusaurus/Docusaurus-guides'
      },
      items: [
        'blog/Docusaurus/Docusaurus-环境配置',
        'blog/Docusaurus/Docusaurus-部署',
        'blog/Docusaurus/Docusaurus-样式与页面',
        'blog/Docusaurus/Docusaurus-自定义组件',
        'blog/Docusaurus/Docusaurus-搜索配置',
        'blog/Docusaurus/Docusaurus-评论系统',
        'blog/Docusaurus/Docusaurus-图床配置',
        'blog/Docusaurus/Docusaurus-文档编辑指南',
        'blog/Docusaurus/Docusaurus-使用Hygen创建文章模板',
        'blog/Docusaurus/docs-template',
      ],
    },
    {
      label: 'Hexo',
      type: 'category',
      link: {
        type: 'doc',
        id: 'blog/Hexo/Hexo-guides'
      },
      items: [
        'blog/Hexo/Hexo-环境配置',
        'blog/Hexo/Hexo-部署',
        'blog/Hexo/Hexo-Vercel部署',
        'blog/Hexo/Hexo-主题安装',
      ],
    },
    {
      label: 'tools',
      type: 'category',
      link: {
        // title: '',
        // description: '记录一些网站的使用小技巧',
        type: 'generated-index',
      },
      items: [
        { 
          type: 'autogenerated',
          dirName: 'blog/Tips',
        },
      ],
    },
  ],
  stack: [
    'stack/introduction',
    
    {
      label: 'Java',
      type: 'category',
      link: {
        type: 'generated-index',
        keywords: ['设计模式'],
      },
      items: [
        {
          label: '设计模式',
          type: 'category',
          link: {
            type: 'doc',
            id: 'stack/java/设计模式/DesignPattern1',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'stack/java/设计模式',
            },
          ],
        },
      ],
    },
    {
      label: 'Git',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'stack/git',
        },
      ],
    },
    {
      label: 'JavaScript',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'stack/js',
        },
      ],
    },
    {
      label: 'Node',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'stack/node',
        },
      ],
    },
    {
      label: 'Css',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'stack/css',
        },
      ],
    },
    {
      label: 'Python',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'stack/python',
        },
      ],
    },
  
    {
      label: 'Docker',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'stack/docker',
        },
      ],
    },
    {
      label: 'database',
      type: 'category',
      link: {
        // title: '',
        // description: '',
        type: 'generated-index',
        keywords: ['database', 'mysql', 'mongodb', 'redis', 'elasticsearch'],
      },
      items: [
        {
          label: 'Mysql',
          type: 'category',
          link: {
            type: 'doc',
            id: 'stack/database/mysql/mysql-note',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'stack/database/mysql',
            },
          ],
        },
        {
          label: 'Redis',
          type: 'category',
          link: {
            type: 'doc',
            id: 'stack/database/redis/redis-note',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'stack/database/redis',
            },
          ],
        },
      ],
    },
  ],
  course: [
    'course/introduction',
    {
      label: '操作系统课设',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'course/OS Course Design',
        },
      ],
    },
    {
      label: '数据结构与算法分析',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        'course/Data Structures And Algorithms/DStart',
        'course/Data Structures And Algorithms/array',
        'course/Data Structures And Algorithms/link',
        'course/Data Structures And Algorithms/recursion',
        'course/Data Structures And Algorithms/queue',
        'course/Data Structures And Algorithms/stack',
        'course/Data Structures And Algorithms/heap',
        'course/Data Structures And Algorithms/binary_tree',
        'course/Data Structures And Algorithms/DStest',
      ],
    },
    {
      label: '高等数学',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'course/Advanced Mathematics',
        },
      ],
    },
  ],
}

module.exports = sidebars
